type=extern
desc=makefile based building (generic)
build_command=make ${ARG1} ${ARG2}
clean_command=make ${ARG1} ${ARG3}
argument1=Common arguments=-f Makefile
argument2=Build arguments=-j ${NUM_PROCS} all
argument3=Clean argumnets=clean
use_return_vale=1
