desc=makefile based building (generic)
extern=true
build_command=make ${ARG1} ${ARG2}
clean_command=make ${ARG1} ${ARG3}
argument1=Common args=-j ${NUM_PROCS} -f Makefile
argument2=Build target=all
argument3=Clean target=clean
use_return_vale=1
