GCC=gcc
OPTS= -DZASKAR -Dpanic=printf -Dckfree=free -Dckalloc=malloc -Dckrealloc=realloc -DHAVE_CONFIG_H -Ihyper -Icommon -Imisc -Icpp/cpplib -I. -O2  
OBJS_DIR=release.lnx

all: ${OBJS_DIR} ../cbrowser

include Makefile.common

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

../cbrowser: ${OBJS}
	${GCC} ${OBJS} -o $@


clean:
	rm -f ../cbrowser 
	rm -f ${OBJS} 