MINGW_DIR=../MinGW
GCC=wine "${MINGW_DIR}"/bin/mingw32-gcc
OPTS= -DZASKAR -Dpanic=printf -Dckfree=free -Dckalloc=malloc -Dckrealloc=realloc -DHAVE_CONFIG_H -Ihyper -Icommon -Imisc -Icpp/cpplib -I. -O2  
OBJS_DIR=release.w32

all: ../cbrowser.exe

include Makefile.common

${OBJS_DIR}:
	mkdir ${OBJS_DIR}
	
../cbrowser.exe: ${OBJS_DIR} ${OBJS}
	${GCC} ${OBJS} -o $@


clean:
	rm -f ../cbrowser.exe
	rm -f ${OBJS}