GCC=gcc
OPTS= -DZASKAR -Dpanic=printf -Dckfree=free -Dckalloc=malloc -Dckrealloc=realloc -DHAVE_CONFIG_H -Ihyper -Icommon -Imisc -Icpp/cpplib -I. -O2  
OBJS_DIR=release.lnx

all: ../bin/cbrowser

include Makefile.common

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

../bin:
	mkdir ../bin

../bin/cbrowser: ../bin ${OBJS_DIR} ${OBJS}
	${GCC} ${OBJS} -o $@


clean:
	rm -f ../bin/cbrowser 
	rm -f ${OBJS} 