GPP=g++
CXXFLAGS=-O2 `wx-config --unicode=no --cppflags`
LIBS=-s -lwx_gtk2_mac-2.8 `wx-config --libs` 
OBJS_DIR=../release.mac

all: ../zinjai

include Makefile.common

clean:
	rm -rf ${OBJS} ../zinjai

../zinjai: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

